### PR TITLE
use void instead of boost::none_t

### PR DESCRIPTION
**Pull request by akrzemi1**
This decouples Boost.Functional from Boost.Optional

### CODE REVIEW

**Comment by danieljames** [comment]
The problem is that it's documented as using boost::none_t (someone might use the default in order to specify the third parameter), so this is technically a breaking change. IMO it would be better to move none_t into 'core' or something similar.

**Comment by akrzemi1** [comment]
I see what you mean. Let's not close this issue yet. Extracting `boost::none_t` to a separate library may also not work. It is too tightly connected to optional. For instance operator<< should work in a compatible way. I will need to rethink it.

**Comment by akrzemi1** [comment]
Would you be OK with a two-phase removal? First, we introduce a second placeholder for a default type; still allow none_t, but make it deprecated. Second (say, after two releases), we remove the dependency?

**Comment by danieljames** [comment]
If none_t must remain in optional, deprecating support for later removal is probably the best route. This will probably affect very few people, if any.

**Comment by danieljames** [comment]
Change in: https://github.com/boostorg/functional/commit/188c8d4c5d0b6be36d6b74855a3d6a72e6c7f444

Since this change isn't a massive problem, I made it immediately, but provided a backwards compatibility macro. That way if this does actually affect anyone, they'll find out sooner, rather than later, but will have an easy workaround if there's an actual problem. Possibly overkill.

**Pull request closed without merging**
